### ISSUE TITLE
초기 세팅 덜되었습니다.

### ISSUE THREAD

**Issue by soheon-lee** [wecode-bootcamp-korea/10-RonWesely-backend#1]
1. requirements.txt 없습니다.
2. settings.py 설정 덜됐습니다. 제일 아래 CORS 관련 허용 부분 누락되었습니다.

**Comment by sincerity10** [comment]
1. requirements.txt 추가
2. settings.py CORS 설정 누락이 아닌 위치 조정 -> 최하단

**Comment by soheon-lee** [comment]
LGTM
